### ISSUE TITLE
Recettage

### ISSUE THREAD

**Issue by ClementGrenierDesrousseaux** [ClementGrenierDesrousseaux/ClementGrenierDesrousseaux_P5_06052022#62]
Front : 

- [x] Etq utilisateur je peux visualiser les différents articles dans l'ordre décroissant de date de création
- [x] Etq utilisateur je peux cliquer sur un article pour voir son contenu
- [x] Etq utilisateur je peux soumettre un commentaire via le formulaire en dessous d'un article #63
- [x] Etq utilisateur je peux envoyer un message de contact via le formulaire de la page "Nous contacter" #64
- [x] Etq utilisateur je peux me connecter en tant qu'admin sur la page de login 
- [x] Etq utilisateur je peux aller voir les réseaux sociaux en cliquant sur leurs icônes #65
- [x] Etq utilisateur je peux télécharger le CV du développeur #66
- [x] Etq utilisateur non connecté, je tombe sur la page de connexion en cliquant sur le lien du BO dans le footer
- [x] Etq utilisateur connecté (admin) je peux aller sur le BO en cliquant sur le lien dans le footer 

Back : 

- [x] Etq admin je peux voir la liste des articles
- [x] Etq admin je peux créer un article
- [x] Etq admin je peux modifier un article
- [x] Etq admin je peux supprimer un article #68
- [x] Etq admin je peux voir la liste des commentaires à approuver #71
- [x] Etq admin je peux approuver un commentaire  #69 
- [x] Etq admin je peux supprimer un commentaire #70 
- [x] Etq admin je peux me déconnecter
